=== SaNuelson/XML-Technology-Project/Project/data.xsd
<?xml version="1.0" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="drm">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="server-info" type="xs:string" />
                <xs:element name="games">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="game" type="TGame" minOccurs="0" maxOccurs="unbounded" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="developers">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="developer" type="TDev" minOccurs="0" maxOccurs="unbounded" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="publishers">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="publisher" type="TPub" minOccurs="0" maxOccurs="unbounded" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="users">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="user" type="TUser" minOccurs="0" maxOccurs="unbounded" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="owner" type="xs:string" use="required" fixed="Multiverse Games" />
        </xs:complexType>

        <xs:key name="gameKey">
            <xs:selector xpath="games/game"/>
            <xs:field xpath="@id-self"/>
        </xs:key>

        <xs:key name="devKey">
            <xs:selector xpath="developers/developer"/>
            <xs:field xpath="@id-self"/>
        </xs:key>

        <xs:key name="pubKey">
            <xs:selector xpath="publishers/publisher"/>
            <xs:field xpath="@id-self"/>
        </xs:key>

        <xs:key name="userKey">
            <xs:selector xpath="users/user"/>
            <xs:field xpath="@id-self"/>
        </xs:key>

    </xs:element>

    <xs:complexType name="TGame">
        <xs:sequence>
            <xs:element name="title" type="TName" />
            <xs:element name="creation-date" type="TMaybeDate" /> <!-- Valid date or "TBA" -->
            <xs:element ref="description"/>
            <xs:element name="reviews">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="review" type="TUserReview" minOccurs="0" maxOccurs="unbounded" />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="achievements" minOccurs="0">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="achievement" type="TAchievement" minOccurs="0" maxOccurs="unbounded" />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="ingame-store" minOccurs="0">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="ingame-item" type="TGameItem" minOccurs="0" maxOccurs="unbounded" />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="id-self" type="IDGame" />
        <xs:attribute name="id-dev" type="IDREFDev" />
        <xs:attribute name="id-pub" type="IDREFPub" use="optional" />
        <xs:attribute name="rating" type="TRating" use="optional" default="RP" />
    </xs:complexType>

    <xs:complexType name="TDev">
        <xs:sequence>
            <xs:element name="name" type="TName" />
            <xs:element name="creation-date" type="xs:date" />
            <xs:element ref="description" />
        </xs:sequence>
        <xs:attribute name="id-self" type="IDDev" />
    </xs:complexType>

    <xs:complexType name="TPub">
        <xs:sequence>
            <xs:element name="name" type="TName" />
            <xs:element name="creation-date" type="xs:date" />
            <xs:element name="plain-description" type="TPlainDescription" />
            <xs:element name="website" minOccurs="0">
                <xs:complexType>
                    <xs:attribute name="url" type="xs:anyURI"/>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="id-self" type="IDPub" />
    </xs:complexType>

    <xs:complexType name="TUser">
        <xs:sequence>
            <xs:element name="email" type="TEmail" />
            <xs:element name="pass-hash" type="TPassHash" />
            <xs:element name="nickname" type="TNickname" />
            <xs:element name="verified" minOccurs="0" />
            <xs:element name="description" type="TMixedDescription" minOccurs="0" />
            <xs:element name="owned-games">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="owned-game" type="TOwnedGame" minOccurs="0" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="id-self" type="IDUser" />
    </xs:complexType>

    <xs:simpleType name="TName">
        <xs:restriction base="xs:string">
            <xs:maxLength value="30" />
            <xs:minLength value="3" />
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="TAchievement">
        <xs:sequence>
            <xs:element name="title" type="TName" />
            <xs:element name="plain-description" type="TPlainDescription" />
            <xs:element name="secret" minOccurs="0" />
            <xs:element name="external-data" type="xs:string" />
            <xs:element name="points" type="xs:nonNegativeInteger" />
        </xs:sequence>
        <xs:attribute name="id-self" type="IDAch" />
    </xs:complexType>

    <xs:complexType name="TGameItem">
        <xs:sequence>
            <xs:element name="title" type="TName" />
            <xs:element name="plain-description" type="TPlainDescription" />
            <xs:element name="external-data" type="xs:string" minOccurs="0" />
            <xs:element name="max-per-user" type="xs:nonNegativeInteger" default="0" />
            <xs:element name="price" type="xs:nonNegativeInteger" />
        </xs:sequence>
        <xs:attribute name="id-self" type="IDItem" />
    </xs:complexType>

    <xs:simpleType name="TPlainDescription">
        <xs:restriction base="xs:string">
            <xs:maxLength value="800" />
            <xs:minLength value="20" />
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="TMixedDescription" mixed="true">
        <xs:sequence>
            <xs:element name="general-reference" type="TGeneralReference" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="TGeneralReference">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="id-reference" type="xs:IDREF" />
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <!-- author, date, text -->
    <xs:complexType name="TUserPost">
        <xs:sequence>
            <xs:element name="creation-date" type="xs:dateTime" />
            <xs:element name="text" type="xs:string" />
        </xs:sequence>
        <xs:attribute name="author" type="IDREFUser" />
    </xs:complexType>

    <!-- TUserPost extended by TUserPost[] -->
    <xs:complexType name="TUserComment">
        <xs:complexContent>
            <xs:extension base="TUserPost">
                <xs:sequence>
                    <xs:element name="reply-section">
                        <xs:complexType>
                            <xs:sequence>
                                <xs:element name="reply" type="TUserPost" minOccurs="0" maxOccurs="unbounded" />
                            </xs:sequence>
                        </xs:complexType>
                    </xs:element>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="TUserReview">
        <xs:complexContent>
            <xs:extension base="TUserPost">
                <xs:sequence>
                    <xs:element name="comment-section">
                        <xs:complexType>
                            <xs:sequence>
                                <xs:element name="comment" type="TUserComment" minOccurs="0" maxOccurs="unbounded" />
                            </xs:sequence>
                        </xs:complexType>
                    </xs:element>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:simpleType name="TEmail">
        <xs:restriction base="xs:string">
            <xs:pattern value="[a-zA-Z0-9_\.\+\-]+@[a-zA-Z0-9\-]+\.[a-zA-Z0-9\-\.]+"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="TPassHash">
        <xs:restriction base="xs:string">
            <xs:minLength value="12" />
            <xs:maxLength value="24" />
            <xs:pattern value="[a-zA-Z0-9.]*" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="TNickname">
        <xs:restriction base="xs:string">
            <xs:maxLength value="20"/>
            <xs:minLength value="5"/>
            <xs:pattern value="([0-9a-zA-Z_-]+ ?)?[0-9a-zA-Z_-]+" />
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="TOwnedGame">
        <xs:sequence>
            <xs:element name="creation-date" type="xs:dateTime" />
            <xs:element name="time-played" type="xs:decimal" />
            <xs:element name="ingame-inventory" minOccurs="0">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="inventory-item" type="TUserItem" minOccurs="0" maxOccurs="unbounded" />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="id-game" type="IDREFGame" />
        <xs:attribute name="id-achs" type="IDREFSAch" />
    </xs:complexType>

    <xs:complexType name="TUserItem">
        <xs:sequence>
            <xs:element name="quantity" type="xs:nonNegativeInteger" />
        </xs:sequence>
        <xs:attribute name="id-item" type="IDREFItem" />
    </xs:complexType>

    <xs:simpleType name="TRating">
        <xs:restriction base="xs:string">
            <xs:enumeration value="E" />
            <xs:enumeration value="E10PLUS" />
            <xs:enumeration value="T" />
            <xs:enumeration value="M" />
            <xs:enumeration value="AO" />
            <xs:enumeration value="RP" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="TMaybeDate">
        <xs:union>
            <xs:simpleType>
                <xs:restriction base="xs:date" />
            </xs:simpleType>
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="TBA" />
                </xs:restriction>
            </xs:simpleType>
        </xs:union>
    </xs:simpleType>

    <!-- IDs -->
    <xs:simpleType name="IDGame">
        <xs:restriction base="xs:ID">
            <xs:pattern value="g-[0-9]+" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="IDAch">
        <xs:restriction base="xs:ID">
            <xs:pattern value="ach-[0-9]+-[0-9]+" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="IDItem">
        <xs:restriction base="xs:ID">
            <xs:pattern value="item-[0-9]+-[0-9]+" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="IDDev">
        <xs:restriction base="xs:ID">
            <xs:pattern value="dev(-[a-z]+)+" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="IDPub">
        <xs:restriction base="xs:ID">
            <xs:pattern value="pub(-[a-z]+)+" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="IDUser">
        <xs:restriction base="xs:ID">
            <xs:pattern value="u-[0-9]+" />
        </xs:restriction>
    </xs:simpleType>

    <!-- IDRefs -->
    <xs:simpleType name="IDREFGame">
        <xs:restriction base="xs:IDREF">
            <xs:pattern value="g-[0-9]+" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="IDREFSAch">
        <xs:restriction base="xs:IDREFS">
            <xs:pattern value="(ach-[0-9]+-[0-9]+ ?)*(ach-[0-9]+-[0-9]+)?" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="IDREFItem">
        <xs:restriction base="xs:IDREF">
            <xs:pattern value="item-[0-9]+-[0-9]+" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="IDREFDev">
        <xs:restriction base="xs:IDREF">
            <xs:pattern value="dev(-[a-z]+)+" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="IDREFPub">
        <xs:restriction base="xs:IDREF">
            <xs:pattern value="pub(-[a-z]+)+" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="IDREFUser">
        <xs:restriction base="xs:IDREF">
            <xs:pattern value="u-[0-9]+" />
        </xs:restriction>
    </xs:simpleType>

    <!-- ref -->
    <xs:element name="description" type="TMixedDescription" />

</xs:schema>

=== SaNuelson/XML-Technology-Project/Project/data.xml
<?xml version="1.0" encoding="UTF-8"?>
<drm owner="Multiverse Games"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="data.xsd">
    <server-info>
		Last update from server at:         <?php echo Date("d.m.Y")?>
    </server-info>
    <games>
        <game id-self="g-1" id-dev="dev-neverlight" rating="E10PLUS">
            <title>Space Scrapper</title>
            <creation-date>TBA</creation-date>
            <description>
				In an intergalactic era, you would think the humanity has finally
				found it's inner peace so to speak. However, there are new dangers
				that await the ever-expanding human race. Extraterrestrial immigrants,
				LGBTS rallies (S stands for Space-kin), and inter-space liberals that
				aim to stomp and destroy all Traditional Values and establich oligarchic
				anarchy upon the galaxy.
				Soon, because of these monstrous intentions, 1st Galactic War took place
				and what used to be a prosperous galactic central, is now but a void
				filled with ashes and scraps of the old world.
				You, as one of the few survivors need to rebuild the civilisation to its
				former glory.
				Embark on your ship into the hostile waste-space, collect resources,
				improve your vessel and root out the bandits that lurk on every corner.
				The Galaxy is counting on you!
            </description>
            <reviews/>
            <achievements>
                <achievement id-self="ach-1-1">
                    <title>Start the game</title>
                    <plain-description>That's right, that's the whole achievo.</plain-description>
                    <secret/>
                    <external-data>ev.onStart</external-data>
                    <points>100</points>
                </achievement>
                <achievement id-self="ach-1-2">
                    <title>Collector</title>
                    <plain-description>Collect 1000 scrap. Seriously it's that easy.</plain-description>
                    <external-data>ge(inv[scrap].quant,1000)</external-data>
                    <points>200</points>
                </achievement>
                <achievement id-self="ach-1-3">
                    <title>Colossus</title>
                    <plain-description>Have a ship of a size at least 150 blocks.</plain-description>
                    <external-data>ge(ship.size,150)</external-data>
                    <points>250</points>
                </achievement>
                <achievement id-self="ach-1-4">
                    <title>Conqueror</title>
                    <plain-description>Visit all 8 main sectors.</plain-description>
                    <external-data>each(map.mainSectors,#.visited)</external-data>
                    <points>450</points>
                </achievement>
            </achievements>
            <ingame-store>
                <ingame-item id-self="item-1-1">
                    <title>Room 1x1</title>
                    <plain-description>Simple small room for your ship.</plain-description>
                    <max-per-user>0</max-per-user>
                    <price>20</price>
                </ingame-item>
                <ingame-item id-self="item-1-2">
                    <title>Room 2x2</title>
                    <plain-description>Simple medium room for your ship.</plain-description>
                    <max-per-user>0</max-per-user>
                    <price>75</price>
                </ingame-item>
                <ingame-item id-self="item-1-3">
                    <title>Room 3x3</title>
                    <plain-description>Simple large room for your ship.</plain-description>
                    <max-per-user>0</max-per-user>
                    <price>165</price>
                </ingame-item>
                <ingame-item id-self="item-1-4">
                    <title>Leeroy Jenkins</title>
                    <plain-description>Unique mercenary for your ship. Make sure he doesn't kill himself.</plain-description>
                    <max-per-user>1</max-per-user>
                    <price>250</price>
                </ingame-item>
            </ingame-store>
        </game>
        <game id-self="g-2" id-dev="dev-neverlight" rating="M">
            <title>The Gunmagedon</title>
            <creation-date>2021-02-01</creation-date>
            <description>
				Have you ever wondered how would a revolver look with incendiary ammo?
				Maybe an acid flamethrower, or a grenade minigun?
				Now's your chance! In this new world driven by gun tinkering and
				prime military engineering, you can create all the weirdest and most
				amazing guns you could ever think of.
				Start your journey in this new, comically hostile world, fight monsters
				and collect mods, and then stick them to your Mastergun. Make the things
				go BOOM!, SPLASH!, RATATATA! or BZZZ! all at the same time in this
				rogue-like gun massacre sandbox.
				Caution: The developers are NOT responsible for any injuries caused by
				excessive experimentation with guns. We strongly advise you to use only
				gun modifications approved by the FUDGE (Fictional Union of Dedicated
				Gun Enthusiasts), which you can find in the User Guide
				                <![CDATA[<link href="https://bit.ly/39yFMpR">here</link>]]>.
            </description>
            <reviews>
                <review author="u-8080">
                    <creation-date>2021-02-01T13:51:39</creation-date>
                    <text>10/10, would kill myself with a wasp-shooting assault rifle again</text>
                    <comment-section/>
                </review>
                <review author="u-1337">
                    <creation-date>2021-02-03T19:22:06</creation-date>
                    <text>
						Found minigun mod, found shotgun mod, found nuclear warhead mod.
						Stuck then together, pressed the shot button.
						My GPU got fried and my house caught on fire.
						I'm currently at my friend's house, gonna try that again.
                    </text>
                    <comment-section/>
                </review>
                <review author="u-4">
                    <creation-date>2021-02-04T00:04:43</creation-date>
                    <text>You can pet the dog.</text>
                    <comment-section>
                        <comment author="u-5">
                            <creation-date>2021-02-04T13:12:11</creation-date>
                            <text>this^</text>
                            <reply-section/>
                        </comment>
                    </comment-section>
                </review>
                <review author="u-7">
                    <creation-date>2021-03-12T16:32:38</creation-date>
                    <text>Difficult but fair. An extremely satisfying ending.</text>
                    <comment-section/>
                </review>
            </reviews>
            <achievements>
                <achievement id-self="ach-2-1">
                    <title>Kill Them All!</title>
                    <plain-description>Kill 2000 enemies. I mean that's the point of this game.</plain-description>
                    <external-data>ge(kills,2000)</external-data>
                    <points>300</points>
                </achievement>
                <achievement id-self="ach-2-2">
                    <title>Dr. OctaBOOM</title>
                    <plain-description>Craft a gun with rocket launcher mod and 7 other mods.</plain-description>
                    <secret/>
                    <external-data>and(any(gun.mods,#.name==RocketLauncher),ge(gun.mods.count,8))</external-data>
                    <points>150</points>
                </achievement>
                <achievement id-self="ach-2-3">
                    <title>GrillMaster</title>
                    <plain-description>Kill 15 enemies with fire projectiles in 8 seconds.</plain-description>
                    <secret/>
                    <external-data>ge(delta(kills.fire,8000),15)</external-data>
                    <points>250</points>
                </achievement>
            </achievements>
            <ingame-store>
                <ingame-item id-self="item-2-1">
                    <title>Rocket Launcher Mod</title>
                    <plain-description>Simple rocket launcher mod.</plain-description>
                    <max-per-user>0</max-per-user>
                    <price>80</price>
                </ingame-item>
                <ingame-item id-self="item-2-2">
                    <title>Minigun Mod</title>
                    <plain-description>Simple minigun mod. Really simple.</plain-description>
                    <max-per-user>0</max-per-user>
                    <price>80</price>
                </ingame-item>
                <ingame-item id-self="item-2-3">
                    <title>Minelayer Mod</title>
                    <plain-description>Simple minelayer mod.</plain-description>
                    <max-per-user>0</max-per-user>
                    <price>80</price>
                </ingame-item>
                <ingame-item id-self="item-2-4">
                    <title>Fragmine</title>
                    <plain-description>Simple fragmine mod.</plain-description>
                    <max-per-user>0</max-per-user>
                    <price>120</price>
                </ingame-item>
                <ingame-item id-self="item-2-5">
                    <title>Cryolator</title>
                    <plain-description>Freezing mod for your gun.</plain-description>
                    <max-per-user>1</max-per-user>
                    <price>250</price>
                </ingame-item>
            </ingame-store>
        </game>
        <game id-self="g-4" id-dev="dev-sugar-powered" rating="T">
            <title>Geneloper</title>
            <creation-date>2021-06-03</creation-date>
            <description>
				In the beginning you created the heavens and the earth.
